/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AccessoriesIndexRouteImport } from './routes/accessories.index'
import { Route as AccessoriesIdRouteImport } from './routes/accessories.$id'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDemosRouteImport } from './routes/admin.demos'
import { Route as AdminExchangesRouteImport } from './routes/admin.exchanges'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPrebookingsRouteImport } from './routes/admin.prebookings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as ApiSeedImagesRouteImport } from './routes/api/seed-images'
import { Route as MobilesIndexRouteImport } from './routes/mobiles.index'
import { Route as MobilesIdRouteImport } from './routes/mobiles.$id'
import { Route as ServiceIndexRouteImport } from './routes/service.index'
import { Route as ServiceTrackRouteImport } from './routes/service.track'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesIndexRoute = AccessoriesIndexRouteImport.update({
  id: '/accessories/',
  path: '/accessories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesIdRoute = AccessoriesIdRouteImport.update({
  id: '/accessories/$id',
  path: '/accessories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemosRoute = AdminDemosRouteImport.update({
  id: '/admin/demos',
  path: '/admin/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExchangesRoute = AdminExchangesRouteImport.update({
  id: '/admin/exchanges',
  path: '/admin/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrebookingsRoute = AdminPrebookingsRouteImport.update({
  id: '/admin/prebookings',
  path: '/admin/prebookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedImagesRoute = ApiSeedImagesRouteImport.update({
  id: '/api/seed-images',
  path: '/api/seed-images',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilesIndexRoute = MobilesIndexRouteImport.update({
  id: '/mobiles/',
  path: '/mobiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilesIdRoute = MobilesIdRouteImport.update({
  id: '/mobiles/$id',
  path: '/mobiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRoute,
} as any)
const ServiceTrackRoute = ServiceTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ServiceRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/exchange': typeof ExchangeRoute
  '/launches': typeof LaunchesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/offers': typeof OffersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service': typeof ServiceRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accessories/$id': typeof AccessoriesIdRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/exchanges': typeof AdminExchangesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/prebookings': typeof AdminPrebookingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/seed-images': typeof ApiSeedImagesRoute
  '/mobiles/$id': typeof MobilesIdRoute
  '/service/track': typeof ServiceTrackRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/mobiles/': typeof MobilesIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/exchange': typeof ExchangeRoute
  '/launches': typeof LaunchesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/offers': typeof OffersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accessories/$id': typeof AccessoriesIdRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/exchanges': typeof AdminExchangesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/prebookings': typeof AdminPrebookingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/seed-images': typeof ApiSeedImagesRoute
  '/mobiles/$id': typeof MobilesIdRoute
  '/service/track': typeof ServiceTrackRoute
  '/accessories': typeof AccessoriesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/mobiles': typeof MobilesIndexRoute
  '/service': typeof ServiceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/exchange': typeof ExchangeRoute
  '/launches': typeof LaunchesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/offers': typeof OffersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service': typeof ServiceRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accessories/$id': typeof AccessoriesIdRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/exchanges': typeof AdminExchangesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/prebookings': typeof AdminPrebookingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/seed-images': typeof ApiSeedImagesRoute
  '/mobiles/$id': typeof MobilesIdRoute
  '/service/track': typeof ServiceTrackRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/mobiles/': typeof MobilesIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/exchange'
    | '/launches'
    | '/llms.txt'
    | '/offers'
    | '/robots.txt'
    | '/service'
    | '/sitemap.xml'
    | '/accessories/$id'
    | '/admin/demos'
    | '/admin/exchanges'
    | '/admin/login'
    | '/admin/prebookings'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reviews'
    | '/admin/sales'
    | '/admin/services'
    | '/api/seed-images'
    | '/mobiles/$id'
    | '/service/track'
    | '/accessories/'
    | '/admin/'
    | '/mobiles/'
    | '/service/'
    | '/api/auth/$'
    | '/api/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/exchange'
    | '/launches'
    | '/llms.txt'
    | '/offers'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/accessories/$id'
    | '/admin/demos'
    | '/admin/exchanges'
    | '/admin/login'
    | '/admin/prebookings'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reviews'
    | '/admin/sales'
    | '/admin/services'
    | '/api/seed-images'
    | '/mobiles/$id'
    | '/service/track'
    | '/accessories'
    | '/admin'
    | '/mobiles'
    | '/service'
    | '/api/auth/$'
    | '/api/files/$'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/compare'
    | '/contact'
    | '/exchange'
    | '/launches'
    | '/llms.txt'
    | '/offers'
    | '/robots.txt'
    | '/service'
    | '/sitemap.xml'
    | '/accessories/$id'
    | '/admin/demos'
    | '/admin/exchanges'
    | '/admin/login'
    | '/admin/prebookings'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reviews'
    | '/admin/sales'
    | '/admin/services'
    | '/api/seed-images'
    | '/mobiles/$id'
    | '/service/track'
    | '/accessories/'
    | '/admin/'
    | '/mobiles/'
    | '/service/'
    | '/api/auth/$'
    | '/api/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ExchangeRoute: typeof ExchangeRoute
  LaunchesRoute: typeof LaunchesRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OffersRoute: typeof OffersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServiceRoute: typeof ServiceRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AccessoriesIdRoute: typeof AccessoriesIdRoute
  AdminDemosRoute: typeof AdminDemosRoute
  AdminExchangesRoute: typeof AdminExchangesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPrebookingsRoute: typeof AdminPrebookingsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  ApiSeedImagesRoute: typeof ApiSeedImagesRoute
  MobilesIdRoute: typeof MobilesIdRoute
  AccessoriesIndexRoute: typeof AccessoriesIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MobilesIndexRoute: typeof MobilesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/': {
      id: '/accessories/'
      path: '/accessories'
      fullPath: '/accessories/'
      preLoaderRoute: typeof AccessoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/$id': {
      id: '/accessories/$id'
      path: '/accessories/$id'
      fullPath: '/accessories/$id'
      preLoaderRoute: typeof AccessoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demos': {
      id: '/admin/demos'
      path: '/admin/demos'
      fullPath: '/admin/demos'
      preLoaderRoute: typeof AdminDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exchanges': {
      id: '/admin/exchanges'
      path: '/admin/exchanges'
      fullPath: '/admin/exchanges'
      preLoaderRoute: typeof AdminExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prebookings': {
      id: '/admin/prebookings'
      path: '/admin/prebookings'
      fullPath: '/admin/prebookings'
      preLoaderRoute: typeof AdminPrebookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-images': {
      id: '/api/seed-images'
      path: '/api/seed-images'
      fullPath: '/api/seed-images'
      preLoaderRoute: typeof ApiSeedImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobiles/': {
      id: '/mobiles/'
      path: '/mobiles'
      fullPath: '/mobiles/'
      preLoaderRoute: typeof MobilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobiles/$id': {
      id: '/mobiles/$id'
      path: '/mobiles/$id'
      fullPath: '/mobiles/$id'
      preLoaderRoute: typeof MobilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/': {
      id: '/service/'
      path: '/'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/service/track': {
      id: '/service/track'
      path: '/track'
      fullPath: '/service/track'
      preLoaderRoute: typeof ServiceTrackRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServiceRouteChildren {
  ServiceTrackRoute: typeof ServiceTrackRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
}

const ServiceRouteChildren: ServiceRouteChildren = {
  ServiceTrackRoute: ServiceTrackRoute,
  ServiceIndexRoute: ServiceIndexRoute,
}

const ServiceRouteWithChildren =
  ServiceRoute._addFileChildren(ServiceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ExchangeRoute: ExchangeRoute,
  LaunchesRoute: LaunchesRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OffersRoute: OffersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServiceRoute: ServiceRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AccessoriesIdRoute: AccessoriesIdRoute,
  AdminDemosRoute: AdminDemosRoute,
  AdminExchangesRoute: AdminExchangesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPrebookingsRoute: AdminPrebookingsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminServicesRoute: AdminServicesRoute,
  ApiSeedImagesRoute: ApiSeedImagesRoute,
  MobilesIdRoute: MobilesIdRoute,
  AccessoriesIndexRoute: AccessoriesIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  MobilesIndexRoute: MobilesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
